FROM python:3.11.2

ENV FLASK_APP=app.py
ENV FLASK_DEBUG=1
ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /code

COPY requirements.txt requirements.txt


RUN    pip3 install --no-cache-dir -r requirements.txt  && \
       useradd -u 1000 micro_s  

COPY . .

RUN chown -R micro_s:micro_s /code 

USER micro_s

CMD ["flask", "run"]
